# для проверки правильности выполнения кода и тем самым быть основой для тестирования
# При помощи assert  вы можете написать тесты и проверить работоспособность своей функции
#
# После каждой проверки через запятую указано сообщение
# которое вы увидите в консоли в случае, если проверка не пройдет
#
# def factorial(x):
#     pr = 1
#     for i in range(2, x + 1):
#         pr *= i
#     return pr
#
#
# assert factorial(1) == 1, '1! должен быть равен 1'
# assert factorial(2) == 2, '2! должен быть равен 2'
# assert factorial(3) == 3, '3! должен быть равен 6'
# assert factorial(4) == 24, '4! должен быть равен 24'
# assert factorial(5) == 120, '5! должен быть равен 120'
#
# print('Тесты пройдены')
#
# Traceback (most recent call last):
#   File "/tmp/sessions/f025d0614c0e65fa/main.py", line 10, in <module>
#     assert factorial(3) == 3, '3! должен быть равен 6'
# AssertionError: 3! должен быть равен 6

